"""Generate moon-phase bias rules from historical win-day analysis.

Reads data/historical/analysis/moon_phase_win_stats.json (produced by
analyze_moon_phases_on_wins.py) and emits system-specific YAML rule files:
  rules/moon_phase_bias_loto6.yaml
  rules/moon_phase_bias_euromillions.yaml

A phase is included as a rule if its observed win % exceeds the expected
uniform %, weighted by how strongly it exceeds expectation:
  - above_expected > 3.0 % → weight 8  (strong signal)
  - above_expected > 1.5 % → weight 6  (moderate signal)
  - above_expected > 0.0 % → weight 4  (weak signal; included for completeness)

The number list boosted by each rule is taken from the corresponding system's
win-day baseline (parsed from the existing win_day_astro_bias_*.yaml files).

Usage::
    python scripts/build_moon_phase_rules.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
STATS_FILE = ROOT / "data" / "historical" / "analysis" / "moon_phase_win_stats.json"
RULES_DIR  = ROOT / "rules"

# Map game name → rule-file suffix and system string used in `when` clauses
GAME_TO_SYSTEM: dict[str, str] = {
    "austria_lotto_6aus45": "loto6",
    "euromillions": "euromillions",
}

# Thresholds → weight mapping (above_expected % → weight)
_WEIGHT_BANDS: list[tuple[float, int]] = [
    (3.0, 8),
    (1.5, 6),
    (0.0, 4),
]

# Phase emoji for reasons
_PHASE_EMOJI: dict[str, str] = {
    "New Moon":        "🌑",
    "Waxing Crescent": "🌒",
    "First Quarter":   "🌓",
    "Waxing Gibbous":  "🌔",
    "Full Moon":       "🌕",
    "Waning Gibbous":  "🌖",
    "Last Quarter":    "🌗",
    "Waning Crescent": "🌘",
}


def _load_baseline_numbers(system: str) -> list[int]:
    """Read the win-day baseline numbers from the existing astro-bias rule file."""
    path = RULES_DIR / f"win_day_astro_bias_{system}.yaml"
    if not path.exists():
        # Fallback: use win_day_bias.yaml global list
        alt = RULES_DIR / "win_day_bias.yaml"
        if alt.exists():
            data = yaml.safe_load(alt.read_text(encoding="utf-8"))
            for mod in data.get("modifiers", []):
                if "values" in mod:
                    return [int(v) for v in mod["values"]]
        return []

    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    for mod in (data.get("modifiers") or []):
        if "baseline" in mod.get("id", ""):
            # values may be a list; YAML anchors are already resolved by pyyaml
            vals = mod.get("values", [])
            if vals:
                return [int(v) for v in vals]
    return []


def _weight_for(above_expected: float) -> int | None:
    """Return weight for the rule, or None if the phase should be excluded."""
    for threshold, weight in _WEIGHT_BANDS:
        if above_expected > threshold:
            return weight
    return None   # below or at expected — exclude


def _phase_id_slug(phase: str) -> str:
    """'Waxing Crescent' → 'waxing_crescent'"""
    return re.sub(r"[^a-z0-9]+", "_", phase.lower()).strip("_")


def build_rules_for_game(game_stats: dict) -> str:
    """Return YAML text for one game's moon-phase bias rules."""
    game_name = game_stats["game"]
    system    = GAME_TO_SYSTEM.get(game_name, game_name)
    baseline  = _load_baseline_numbers(system)
    total     = game_stats["total_wins"]
    phases    = game_stats["phases"]           # already sorted by pct desc

    modifiers: list[dict] = []

    for p in phases:
        above = p["above_expected"]
        weight = _weight_for(above)
        if weight is None:
            continue

        phase      = p["phase"]
        count      = p["count"]
        pct        = p["pct"]
        slug       = _phase_id_slug(phase)
        emoji      = _PHASE_EMOJI.get(phase, "")
        rule_id    = f"moon_phase_{slug}_{system}"
        direction  = "above" if above >= 0 else "below"

        reason = (
            f"{emoji} Moon Phase bias ({system}): {phase} appeared on "
            f"{count}/{total} jackpot-win days ({pct:.1f}% vs {p['expected_pct']:.1f}% expected, "
            f"{abs(above):.1f}% {direction} expected); boost win-day numbers when today matches."
        )

        modifiers.append({
            "id": rule_id,
            "when": f"system == '{system}' and moon_phase.phase == '{phase}'",
            "action": "add_many",
            "values": baseline,
            "weight": weight,
            "reason": reason,
        })

    doc = {
        "# generated by": "scripts/build_moon_phase_rules.py",
        "# source": str(STATS_FILE.relative_to(ROOT)),
        "modifiers": modifiers,
    }

    # Build header comment + YAML body
    header = (
        f"# Moon-phase bias rules for {system}\n"
        f"# Generated by scripts/build_moon_phase_rules.py\n"
        f"# Source: data/historical/analysis/moon_phase_win_stats.json\n"
        f"# Total jackpot-win days analysed: {total}\n"
        f"# Only phases above expected frequency are included.\n"
        f"#\n"
        f"# Weight bands:\n"
        f"#   above_expected > 3.0% → weight 8\n"
        f"#   above_expected > 1.5% → weight 6\n"
        f"#   above_expected > 0.0% → weight 4\n"
    )

    yaml_body = yaml.dump(
        {"modifiers": modifiers},
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        width=120,
    )

    return header + yaml_body


def main() -> None:
    if not STATS_FILE.exists():
        raise SystemExit(
            f"Missing {STATS_FILE}.\n"
            "Run: python scripts/analyze_moon_phases_on_wins.py"
        )

    stats: list[dict] = json.loads(STATS_FILE.read_text(encoding="utf-8"))

    for game_stats in stats:
        game_name = game_stats["game"]
        system    = GAME_TO_SYSTEM.get(game_name, game_name)
        out_path  = RULES_DIR / f"moon_phase_bias_{system}.yaml"

        text = build_rules_for_game(game_stats)
        out_path.write_text(text, encoding="utf-8")

        # Count rules emitted
        n_rules = text.count("\n- id:")
        dominant = [
            p for p in game_stats["phases"] if p["above_expected"] > 0
        ]
        print(
            f"✓ {out_path.name}: {n_rules} rule(s) — dominant phases: "
            + ", ".join(f"{p['phase']} ({p['pct']:.1f}%)" for p in dominant[:4])
        )


if __name__ == "__main__":
    main()
